export const EVENT_KEYS = {
    QUIT_GAME: 'QUIT_GAME',
    WATCH_ADS_GET_MORE_PLAY: 'WATCH_ADS_GET_MORE_PLAY',
}

//Watch ads to get more plays.

export const MESSAGE_KEYS = {
    WATCH_ADS_GET_MORE_PLAY_OKE: 'WATCH_ADS_GET_MORE_PLAY_OKE',
    WATCH_ADS_GET_MORE_PLAY_FAILED: 'WATCH_ADS_GET_MORE_PLAY_FAILED',
    PAUSE_SOUND: 'PAUSE_SOUND',
    RESUME_SOUND: 'RESUME_SOUND',
}
