export const BRIDGE_EVENT_KEYS = {
    WEB_TO_RN: {
        QUIT_GAME: 'QUIT_GAME',
        WATCH_ADS_GET_MORE_PLAY: 'WATCH_ADS_GET_MORE_PLAY',

        START_GAME: 'START_GAME',
        UPDATE_SCORE: 'UPDATE_SCORE',
        RESUME_GAME: 'RESUME_GAME'
    },
    RN_TO_WEB: {
        WATCH_ADS_GET_MORE_PLAY_OKE: 'WATCH_ADS_GET_MORE_PLAY_OKE',
        WATCH_ADS_GET_MORE_PLAY_FAILED: 'WATCH_ADS_GET_MORE_PLAY_FAILED',
        PAUSE_SOUND: 'PAUSE_SOUND',
        RESUME_SOUND: 'RESUME_SOUND',

        START_GAME_OKE: 'START_GAME_OKE',
        START_GAME_FAILED: 'START_GAME_FAILED',
    }
}